name: CSI2115 Linux Kernel

on:
  push:
    paths:
      - 'linux'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Build Linux Kernel
        shell: bash
        run: |
          wget "https://github.com/hgleeY/linux/archive/$(git rev-parse HEAD:linux).zip"
          unzip "linux-$(git rev-parse HEAD:linux).zip"
          ./build-linux.sh "linux-$(git rev-parse HEAD:linux)" tinyconfig

