name: CSI2115 Linux Kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download linux
        run: wget https://github.com/hgleeY/linux/archive/$(git rev-parse HEAD:linux).zip

      - name: Unzip linux
        run: unzip -q linux-$(git rev-parse HEAD:linux).zip

      - name: Build linux
        run: ./build-linux.sh linux-$(git rev-parse HEAD:linux) tinyconfig

