name: Test Linux Kernel

on:
  push:
    paths:
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test linux
        run: make -C test

